export const COMMENTS = [
  {
    id: 0,
    beachsiteId: 0,
    rating: 5,
    text: "The water was clean and clear, and there were plenty of activities for me to do on the beach: swimming, surfing, reading a book, playing volleyball… the list goes on.",
    author: "Laxman Sashka",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    beachsiteId: 0,
    rating: 3,
    text: "This crazy monkey kept following us back to our resort.",
    author: "Marita Idir",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    beachsiteId: 0,
    rating: 4,
    text: "Do not drink the seawater. It isn't as clean as you would think.",
    author: "Philip Joby",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    beachsiteId: 0,
    rating: 3,
    text: "Don't forget to bring suntan lotion... This is my first time taking a vacation, nobody told me that the office and beach had different lighting!",
    author: "Lizzie Ruzan",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    beachsiteId: 0,
    rating: 5,
    text: "This has been our favorite resort for over 7 years. It is an absolutely beautiful site. The staff are very friendly and helpful. Don't forget to try out the pool.",
    author: "R. E. Lucas",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    beachsiteId: 1,
    rating: 5,
    text: "Wow..Just wow... I think I will stay for another year. The villas are so beautiful and everything I need is close by.",
    author: "Lily Tatianna",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    beachsiteId: 1,
    rating: 1,
    text: "If you're looking for an opportunity to reconnect with friends and family while getting some sun and exercise in nature, I would highly recommend working from your own backyard!",
    author: "Ted Downs",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    beachsiteId: 1,
    rating: 5,
    text: "The villas were nice, but I felt like they were a little too big. It would be better to come with others.",
    author: "Jayne McLaughlin",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    beachsiteId: 1,
    rating: 4,
    text: "The villas a excellent, but I found the beach to be a bit boring after a few weeks.",
    author: "Darlene Simong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    beachsiteId: 1,
    rating: 5,
    text: "It's so relaxing and peaceful. I feel like I'm in my own little bubble of calm, and everyone else is just kind of like a part of the scenery. There are no distractions, just waves and birds and sunsets. It's amazing how much peace you can find on a beach!",
    author: "Stuart Lozano",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 10,
    beachsiteId: 2,
    rating: 5,
    text: "I had a great time working from an island. It was so nice to have the freedom to get up early, take a walk around the island, or go for a run. The weather was also really lovely, as we had sunshine almost every day.",
    author: "Maurice Wilkerson",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    beachsiteId: 2,
    rating: 1,
    text: "We had a family emergency and had to leave the island, but the was no way off until morning! Think about emergencies, please!",
    author: "John and Rene Peterson",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 12,
    beachsiteId: 2,
    rating: 5,
    text: "I would recommend working from an island if you want to be able to do your job while still being able to enjoy nature and relax when you need it. It's a great balance between getting outside and being productive!",
    author: "Joann Foley",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    beachsiteId: 2,
    rating: 4,
    text: "It was a great place to work, but it was a bit isolated... I had some trouble getting things I need for my diet",
    author: "Kenneth Brown",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    beachsiteId: 2,
    rating: 5,
    text: "Working from an island is a dream come true. I love the seclusion, but I also love the ability to be in touch with the outside world and have access to so many resources. It's really nice to have access to people who can help me figure out if I need something shipped.",
    author: "Sonia Osborne",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 15,
    beachsiteId: 3,
    rating: 4,
    text: "It was great, but being here made it a little difficult to feel motivated to work.",
    author: "Merle Jensen",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 16,
    beachsiteId: 3,
    rating: 5,
    text: "I love working from the beach.",
    author: "Lori Ware",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    beachsiteId: 3,
    rating: 5,
    text: "I would definitely recommend working from the beach if you're looking for a change of pace from your regular office routine.",
    author: "Kirk McCann",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    beachsiteId: 3,
    rating: 4,
    text: "I love working from a beach bungalow. The atmosphere is relaxed and laid back, which is perfect for me. I can't imagine having to work in an office all day long, but I also don't want to feel like I'm missing out on anything either. A beach bungalow is the perfect balance of relaxed and productive—and it's exactly what I need!",
    author: "Jay Roth",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    beachsiteId: 3,
    rating: 5,
    text: "We had a blast working from the beach bungalow!",
    author: "Tom Tomas",
    date: "2019-02-18T18:12Z",
  },
];
